- name: Create master public ip
  azure_rm_publicipaddress:
    resource_group: az_k8s_cluster
    allocation_method: Static
    name: masterpublicip001


- name: Create Master NIC
  azure_rm_networkinterface:
    resource_group: az_k8s_cluster
    name: masternic001
    virtual_network: mastervn001
    subnet: mastersubnet001
    public_ip_name: masterpublicip001
    security_group: secgroup001

- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: az_k8s_cluster
    name: master
    vm_size: Standard_B2s
    storage_account: k8azstorage
    storage_container: mastervm001
    storage_blob: mastervm001.vhd
    admin_username: azureuser
    admin_password: Password1234!
    network_interfaces: masternic001
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
