- name: Create resource group
  azure_rm_resourcegroup:
     name: az_k8s_cluster
     location: "eastus"
     tags:
       env: testing
  tags:
     - recipe4

- name: Create storage account
  azure_rm_storageaccount:
    resource_group: az_k8s_cluster
    name: k8azstorage
    account_type: Standard_LRS

- name: Create  virtual network
  azure_rm_virtualnetwork:
    resource_group: az_k8s_cluster
    name: mastervn001
    address_prefixes: "10.0.0.0/16"

- name: Add  Master subnet
  azure_rm_subnet:
    resource_group: az_k8s_cluster
    name: mastersubnet001
    address_prefix: "10.0.1.0/24"
    virtual_network: mastervn001

- name: Add  Wrker1 subnet
  azure_rm_subnet:
    resource_group: az_k8s_cluster
    name: workersubnet001
    address_prefix: "10.0.2.0/24"
    virtual_network: mastervn001

- name: Add worker2  subnet
  azure_rm_subnet:
    resource_group: az_k8s_cluster
    name: workersubnet002
    address_prefix: "10.0.3.0/24"
    virtual_network: mastervn001

- name: Create security group that allows SSH
  azure_rm_securitygroup:
    resource_group: az_k8s_cluster
    name: secgroup001
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: apiserver
        protocol: Tcp
        destination_port_range: 6443
        access: Allow
        priority: 110
        direction: Inbound
      - name: etcdserver
        protocol: Tcp
        destination_port_range: 2379-2380
        access: Allow
        priority: 111
        direction: Inbound
      - name: kubelet
        protocol: Tcp
        destination_port_range: 10250
        access: Allow
        priority: 112
        direction: Inbound
      - name: kubescheduler
        protocol: Tcp
        destination_port_range: 10251
        access: Allow
        priority: 113
        direction: Inbound
      - name: kubecontroller
        protocol: Tcp
        destination_port_range: 10252
        access: Allow
        priority: 114
        direction: Inbound
      - name: nodeports
        protocol: Tcp
        destination_port_range: 30000-32767
        access: Allow
        priority: 115
        direction: Inbound     
