---
- hosts: localhost
  become: false
  gather_facts: no
  connection: local
  vars:
     ansible_user: azureuser
     ansible_password: Password1234!
     ansible_sudo_pass: Password1234!
  roles:
     - { role: az_resourcegroup }
     - { role: az_role }
