---
- hosts: localhost
  gather_facts: no
  become: true
  connection: local
  vars:
      users:
      - services
      - gameserver
  tasks:
     - name: Create service accounts
       user:
          name: services
          uid: 9998

     - name: Create user accounts
       user:
          name: gameserver
          uid: 7777
          
     - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
       user:
          name: "{{ item }}"
          generate_ssh_key: yes
          ssh_key_bits: 2048
          ssh_key_file: .ssh/id_rsa
       with_items: "{{ users }}"
     - name: touch file libsigar-amd64-linux.so
       file:
           path: /usr/local/lib/libsigar-amd64-linux.so
           state: touch
